#include <Windows.h>
#include <tchar.h>

#define NUMLINES ((int) (sizeof sysmetrics / sizeof sysmetrics [0]))

struct {
	int Index;
	TCHAR * szLabel;
	TCHAR * szDesc;
} sysmetrics[] = {
	SM_CXSCREEN, _T("SM_CXSCREEN"), _T("Screen width in pixels"),
	SM_CYSCREEN, _T("SM_CYSCREEN"), _T("Screen height in pixels"),
	SM_CXVSCROLL, _T("SM_CXVSCROLL"), _T("Vertical scroll width"),
	SM_CYHSCROLL, _T("SM_CYHSCROLL"), _T("Horizontal scroll height"),
	SM_CYCAPTION, _T("SM_CYCAPTION"), _T("Caption bar height"),
	SM_CXBORDER, _T("SM_CXBORDER"), _T("Window border width"),
	SM_CYBORDER, _T("SM_CYBORDER"), _T("Window border height"),
	SM_CXFIXEDFRAME, _T("SM_CXFIXEDFRAME"), _T("Dialog window frame width"),
	SM_CYFIXEDFRAME, _T("SM_CYFIXEDFRAME"), _T("Dialog window frame height"),
	SM_CYVTHUMB, _T("SM_CYVTHUMB"), _T("Vertical scroll thumb height"),
	SM_CXHTHUMB, _T("SM_CXHTHUMB"), _T("Horizontal scroll thumb width"),
	SM_CXICON, _T("SM_CXICON"), _T("Icon width"),
	SM_CYICON, _T("SM_CYICON"), _T("Icon height"),
	SM_CXCURSOR, _T("SM_CXCURSOR"), _T("Cursor width"),
	SM_CYCURSOR, _T("SM_CYCURSOR"), _T("Cursor height"),
	SM_CYMENU, _T("SM_CYMENU"), _T("Menu bar height"),
	SM_CXFULLSCREEN, _T("SM_CXFULLSCREEN"), _T("Full screen client area width"),
	SM_CYFULLSCREEN, _T("SM_CYFULLSCREEN"), _T("Full screen client area height"),
	SM_CYKANJIWINDOW, _T("SM_CYKANJIWINDOW"), _T("Kanji window height"),
	SM_MOUSEPRESENT, _T("SM_MOUSEPRESENT"), _T("Mouse present flag"),
	SM_CYVSCROLL, _T("SM_CYVSCROLL"), _T("Vertical scroll arrow height"),
	SM_CXHSCROLL, _T("SM_CXHSCROLL"), _T("Horizontal scroll arrow width"),
	SM_DEBUG, _T("SM_DEBUG"), _T("Debug version flag"),
	SM_SWAPBUTTON, _T("SM_SWAPBUTTON"), _T("Mouse buttons swapped flag"),
	SM_CXMIN, _T("SM_CXMIN"), _T("Minimum window width"),
	SM_CYMIN, _T("SM_CYMIN"), _T("Minimum window height"),
	SM_CXSIZE, _T("SM_CXSIZE"), _T("Min/Max/Close button width"),
	SM_CYSIZE, _T("SM_CYSIZE"), _T("Min/Max/Close button height"),
	SM_CXSIZEFRAME, _T("SM_CXSIZEFRAME"), _T("Window sizing frame width"),
	SM_CYSIZEFRAME, _T("SM_CYSIZEFRAME"), _T("Window sizing frame height"),
	SM_CXMINTRACK, _T("SM_CXMINTRACK"), _T("Minimum window tracking width"),
	SM_CYMINTRACK, _T("SM_CYMINTRACK"), _T("Minimum window tracking height"),
	SM_CXDOUBLECLK, _T("SM_CXDOUBLECLK"), _T("Double click x tolerance"),
	SM_CYDOUBLECLK, _T("SM_CYDOUBLECLK"), _T("Double click y tolerance"),
	SM_CXICONSPACING, _T("SM_CXICONSPACING"), _T("Horizontal icon spacing"),
	SM_CYICONSPACING, _T("SM_CYICONSPACING"), _T("Vertical icon spacing"),
	SM_MENUDROPALIGNMENT, _T("SM_MENUDROPALIGNMENT"), _T("Left or right menu drop"),
	SM_PENWINDOWS, _T("SM_PENWINDOWS"), _T("Pen extensions installed"),
	SM_DBCSENABLED, _T("SM_DBCSENABLED"), _T("Double-Byte Char Set enabled"),
	SM_CMOUSEBUTTONS, _T("SM_CMOUSEBUTTONS"), _T("Number of mouse buttons"),
	SM_SECURE, _T("SM_SECURE"), _T("Security present flag"),
	SM_CXEDGE, _T("SM_CXEDGE"), _T("3-D border width"),
	SM_CYEDGE, _T("SM_CYEDGE"), _T("3-D border height"),
	SM_CXMINSPACING, _T("SM_CXMINSPACING"), _T("Minimized window spacing width"),
	SM_CYMINSPACING, _T("SM_CYMINSPACING"), _T("Minimized window spacing height"),
	SM_CXSMICON, _T("SM_CXSMICON"), _T("Small icon width"),
	SM_CYSMICON, _T("SM_CYSMICON"), _T("Small icon height"),
	SM_CYSMCAPTION, _T("SM_CYSMCAPTION"), _T("Small caption height"),
	SM_CXSMSIZE, _T("SM_CXSMSIZE"), _T("Small caption button width"),
	SM_CYSMSIZE, _T("SM_CYSMSIZE"), _T("Small caption button height"),
	SM_CXMENUSIZE, _T("SM_CXMENUSIZE"), _T("Menu bar button width"),
	SM_CYMENUSIZE, _T("SM_CYMENUSIZE"), _T("Menu bar button height"),
	SM_ARRANGE, _T("SM_ARRANGE"), _T("How minimized windows arranged"),
	SM_CXMINIMIZED, _T("SM_CXMINIMIZED"), _T("Minimized window width"),
	SM_CYMINIMIZED, _T("SM_CYMINIMIZED"), _T("Minimized window height"),
	SM_CXMAXTRACK, _T("SM_CXMAXTRACK"), _T("Maximum draggable width"),
	SM_CYMAXTRACK, _T("SM_CYMAXTRACK"), _T("Maximum draggable height"),
	SM_CXMAXIMIZED, _T("SM_CXMAXIMIZED"), _T("Width of maximized window"),
	SM_CYMAXIMIZED, _T("SM_CYMAXIMIZED"), _T("Height of maximized window"),
	SM_NETWORK, _T("SM_NETWORK"), _T("Network present flag"),
	SM_CLEANBOOT, _T("SM_CLEANBOOT"), _T("How system was booted"),
	SM_CXDRAG, _T("SM_CXDRAG"), _T("Avoid drag x tolerance"),
	SM_CYDRAG, _T("SM_CYDRAG"), _T("Avoid drag y tolerance"),
	SM_SHOWSOUNDS, _T("SM_SHOWSOUNDS"), _T("Present sounds visually"),
	SM_CXMENUCHECK, _T("SM_CXMENUCHECK"), _T("Menu check-mark width"),
	SM_CYMENUCHECK, _T("SM_CYMENUCHECK"), _T("Menu check-mark height"),
	SM_SLOWMACHINE, _T("SM_SLOWMACHINE"), _T("Slow processor flag"),
	SM_MIDEASTENABLED, _T("SM_MIDEASTENABLED"), _T("Hebrew and Arabic enabled flag"),
	SM_MOUSEWHEELPRESENT, _T("SM_MOUSEWHEELPRESENT"), _T("Mouse wheel present flag"),
	SM_XVIRTUALSCREEN, _T("SM_XVIRTUALSCREEN"), _T("Virtual screen x origin"),
	SM_YVIRTUALSCREEN, _T("SM_YVIRTUALSCREEN"), _T("Virtual screen y origin"),
	SM_CXVIRTUALSCREEN, _T("SM_CXVIRTUALSCREEN"), _T("Virtual screen width"),
	SM_CYVIRTUALSCREEN, _T("SM_CYVIRTUALSCREEN"), _T("Virtual screen height"),
	SM_CMONITORS, _T("SM_CMONITORS"), _T("Number of monitors"),
	SM_SAMEDISPLAYFORMAT, _T("SM_SAMEDISPLAYFORMAT"), _T("Same color format flag")
};